### ISSUE TITLE
The Hanken Corpus of Academic Writing

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#119]
http://urn.fi/urn:nbn:fi:lb-2016081504

- [x] Not in VLO

**Comment by eaxelson** [comment]
No access URN.

**Comment by jakoble** [comment]
I suppose the corpus has not yet been released, given the "Under Negotiation" licence.

**Comment by tosaja** [comment]
Should it be in VLO if it has not been published?

**Comment by lennes** [comment]
We originally learned about this corpus via a survey conducted by the Faculty of Humanities at UHEL in 2016, aiming to gather information about resources collected within the Faculty. The rightholder of the data stated back then that the corpus would be published on GitHub. This seems unlikely to have happened, and unless it did, the data might no longer exist. Nowadays, there would also be GDPR issues involved.  The corpus might have been sort of "upcoming" in the Language Bank of Finland at some point in the past, but is no longer, to be realistic. 

It is correct that this resource should not be shown on VLO. We should not be advertising a persistent identifier for it, either, since we do not know what entity the PID refers to, if any. (Still ,we could try contacting the rightholder to see if they still have data they would like and could legally deposit with the Language Bank.)

@jakoble, since it is OK that this resource is not on VLO, could you please close this issue? Thanks :)
