### ISSUE TITLE
AddictionLink in Finnish Sign Language

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#397]
http://urn.fi/urn:nbn:fi:lb-2014073022

- [ ] Missing size
- [ ] Unclear annotation

**Comment by tosaja** [comment]
Are these still existing issues after migrating from Metashare?

**Comment by lennes** [comment]
The metadata record points to a non-existent page on a website of an external organization. The content that was originally linked via the "access location" URL is no longer available. We should remove the metadata record altogether, since it is both broken and unwarranted. @jakoble, please close this issue and make sure the record is not included in any Resource Families. Thanks :)

**Comment by jakoble** [comment]
Deleted from the backend; thanks, Mietta!
