### ISSUE TITLE
JRC-Acquis Multilingual Parallel Corpus

### ISSUE THREAD

**Issue by jakoble** [clarin-eric/resource-families-issues#43]
https://ec.europa.eu/jrc/en/language-technologies/jrc-acquis

- Metadata issue:
  - [x] Unknown licence

**Comment by TomazErjavec** [comment]
No true, the licence is known and given on the landing page, cited above, cf.
https://ec.europa.eu/jrc/en/language-technologies/jrc-acquis#Usage%20conditions%20/%20Licensing%20issues

**Comment by twagoo** [comment]
I agree that the licence information is represented well in the metadata as well as the landing page. Mapping to VLO fields could be improved, i.e. the `downloadLocation` of the licence info component is not mapped to a licence URL. I would need to have a closer look into this to find out where the problem lies exactly.
